/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.tela;

import br.com.entidade.Cliente;



/**
 *
 * @author IEE-NOT-61
 */
public class TelaPrincipal extends javax.swing.JFrame {

   private Cliente cliente;
   
    public TelaPrincipal() {
        initComponents();
    }
     public TelaPrincipal(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        varUsuarioLogado.setText("Bem vindo(a) " + cliente.getNome());
        if(varUsuarioLogado.isEnabled()){
            varConsumacao.setVisible(true);
//            new AlteraSenhaUsuario(usuario).setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        varUsuarioLogado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_clientes = new javax.swing.JMenu();
        item_cad_clientes = new javax.swing.JMenuItem();
        pesquisar_cliente = new javax.swing.JMenuItem();
        menu_produtos = new javax.swing.JMenu();
        item_cad_produto = new javax.swing.JMenuItem();
        item_pes_produtos = new javax.swing.JMenuItem();
        recarregar_comanda = new javax.swing.JMenu();
        item_recarregar_comanda = new javax.swing.JMenuItem();
        varConsumacao = new javax.swing.JMenu();
        realizar_consumacao = new javax.swing.JMenuItem();
        leitor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Senac");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        varUsuarioLogado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/senac logo menor II.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(varUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel2)
                .addGap(91, 91, 91)
                .addComponent(varUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenuBar1.setForeground(new java.awt.Color(153, 153, 153));

        menu_clientes.setBackground(new java.awt.Color(153, 153, 153));
        menu_clientes.setForeground(new java.awt.Color(0, 85, 148));
        menu_clientes.setText("Cliente");
        menu_clientes.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        item_cad_clientes.setBackground(new java.awt.Color(153, 153, 153));
        item_cad_clientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item_cad_clientes.setText("Cadastrar");
        item_cad_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cad_clientesActionPerformed(evt);
            }
        });
        menu_clientes.add(item_cad_clientes);

        pesquisar_cliente.setBackground(new java.awt.Color(153, 153, 153));
        pesquisar_cliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pesquisar_cliente.setText("Pesquisar");
        pesquisar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisar_clienteActionPerformed(evt);
            }
        });
        menu_clientes.add(pesquisar_cliente);

        jMenuBar1.add(menu_clientes);

        menu_produtos.setForeground(new java.awt.Color(0, 85, 148));
        menu_produtos.setText("Produtos");
        menu_produtos.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        item_cad_produto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item_cad_produto.setText("Cadastrar");
        item_cad_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cad_produto(evt);
            }
        });
        menu_produtos.add(item_cad_produto);

        item_pes_produtos.setBackground(new java.awt.Color(153, 153, 153));
        item_pes_produtos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item_pes_produtos.setText("Pesquisar");
        item_pes_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_pes_produtosActionPerformed(evt);
            }
        });
        menu_produtos.add(item_pes_produtos);

        jMenuBar1.add(menu_produtos);

        recarregar_comanda.setForeground(new java.awt.Color(0, 85, 148));
        recarregar_comanda.setText("Recarga");
        recarregar_comanda.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        item_recarregar_comanda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item_recarregar_comanda.setText("Recarregar Comanda");
        item_recarregar_comanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_recarregar_comandaActionPerformed(evt);
            }
        });
        recarregar_comanda.add(item_recarregar_comanda);

        jMenuBar1.add(recarregar_comanda);

        varConsumacao.setForeground(new java.awt.Color(0, 85, 148));
        varConsumacao.setText("Consumação");
        varConsumacao.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        realizar_consumacao.setBackground(new java.awt.Color(153, 153, 153));
        realizar_consumacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        realizar_consumacao.setText("Realizar Consumação");
        realizar_consumacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizar_consumacaoActionPerformed(evt);
            }
        });
        varConsumacao.add(realizar_consumacao);

        jMenuBar1.add(varConsumacao);

        leitor.setText("Leitor QRCode");
        leitor.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("QRCode");
        leitor.add(jMenuItem1);

        jMenuBar1.add(leitor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_cad_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cad_clientesActionPerformed
        // TODO add your handling code here:
        new CadastrarCliente().setVisible(true);
    }//GEN-LAST:event_item_cad_clientesActionPerformed

    private void item_recarregar_comandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_recarregar_comandaActionPerformed
        new RecarregarComanda().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_item_recarregar_comandaActionPerformed

    private void pesquisar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisar_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisar_clienteActionPerformed

    private void item_pes_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_pes_produtosActionPerformed
        // TODO add your handling code here:
        new PesquisarProduto().setVisible(true);
    }//GEN-LAST:event_item_pes_produtosActionPerformed

    private void item_cad_produto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cad_produto
        // TODO add your handling code here:
        new CadastrarProduto().setVisible(true);
    }//GEN-LAST:event_item_cad_produto

    private void realizar_consumacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizar_consumacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizar_consumacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_cad_clientes;
    private javax.swing.JMenuItem item_cad_produto;
    private javax.swing.JMenuItem item_pes_produtos;
    private javax.swing.JMenuItem item_recarregar_comanda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu leitor;
    private javax.swing.JMenu menu_clientes;
    private javax.swing.JMenu menu_produtos;
    private javax.swing.JMenuItem pesquisar_cliente;
    private javax.swing.JMenuItem realizar_consumacao;
    private javax.swing.JMenu recarregar_comanda;
    private javax.swing.JMenu varConsumacao;
    private javax.swing.JLabel varUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
